<a href="https://colab.research.google.com/github/MaheshwariV-rguktiiit/Assignment-3/blob/master/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Task 1:**

1.Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [1]:

def compute(a, b): 
	try: 
		result = a / b 
		print(" Your answer is :", result) 
	except ZeroDivisionError: 
		print("Sorry ! You are dividing by zero ") 

# Look at parameters and note the working of Program 
compute(5, 0)
compute(3, 2)
compute(6, 3)
compute(4, 0)
compute(7, 5)
compute(345, 0)
compute(0, 345)

Sorry ! You are dividing by zero 
 Your answer is : 1.5
 Your answer is : 2.0
Sorry ! You are dividing by zero 
 Your answer is : 1.4
Sorry ! You are dividing by zero 
 Your answer is : 0.0


2.Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 

In [4]:
subjects = ["Americans","Indians"]
verbs = ["play","watch"]
objects = ["baseball","cricket"]

for l in subjects:
    
    for m in verbs:
               
        for n in objects:
            print(l, m, n, end = ".")
            print()

Americans play baseball.
Americans play cricket.
Americans watch baseball.
Americans watch cricket.
Indians play baseball.
Indians play cricket.
Indians watch baseball.
Indians watch cricket.


### **Task 2 :**
 

1.Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 
 
 

In [11]:
import numpy as np
x = np.array([1,2,3,4])
N = 3
print(np.vander(x,),"\n")
print(np.vander(x, increasing=True),"\n")
print(np.vander(x, N) , "\n")
print(np.vander(x,N, increasing = True), "\n")
print(np.column_stack([x**(N-i-1) for i in range(N)]), "\n")
#The determinant of a square Vandermonde matrix is the product of the differences between the values of the input vector:
print(np.linalg.det(np.vander(x)),"\n")
print((4-3)*(4-2)*(4-1)*(3-2)*(3-1)*(2-1))

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]] 

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]] 

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]] 

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 

12.00000000000001 

12
